### ISSUE TITLE
Missing HTTP Resource cleanup/closing in executeRequest()

### ISSUE THREAD

**Issue by manuelAldana** [phonedeck/gcm4j#6]
I am using gcm4j (thanks for it) and am debugging due to (rarely) happening push instabilities. 

What I stumbled upon:
https://github.com/phonedeck/gcm4j/blob/master/src/main/java/com/phonedeck/gcm4j/AbstractDefaultGcm.java#L103

Inside executeRequest() I don't see any releasing of connection resources (either close() Input|OutputStream or disconnect on the connection. Is this on purpose, did I overlook some resource-cleanup code? If so, just close this issue.

Further more, per default I don't see any default connection pooling. Is this recommended by gcm (unfortunately I cannot find anything in gcm-documentation)?

**Comment by egergo** [comment]
Hi Manuel,

there are two things to see here: firstly the input and output streams are closed by Java 7's try-with-resource statement. When all the streams are closed, Java marks this connection as reusable. Which leads to the second point: pooling is solved by Java. HTTPURLConnections follow the recommendations in the HTTP 2 standard regarding keep-alive connections and maximum number of connections towards a server. This means that if you properly close the streams, don't call disconnect on the connection, Java takes care of everything.

**Comment by manuelAldana** [comment]
Thanks for response. I indeed missed the syntactic sugar of try-with-resource. Interesting, the keep-alive connections feature of HttpUrlConnection was new to me (http://docs.oracle.com/javase/6/docs/technotes/guides/net/http-keepalive.html). Too long working directly with apache's http-client so missed this java in-house feature ;)
