### ISSUE TITLE
Notification payload in the API

### ISSUE THREAD

**Issue by juhovh** [phonedeck/gcm4j#7]
In GcmRequest I can only see support for data payload, how about the notification payload as described in https://developers.google.com/cloud-messaging/server-ref#notification-payload-support document? This is not really critical for me, just curious because Google seems to have updated their documentation quite a bit and added iOS support too.

**Comment by egergo** [comment]
https://github.com/phonedeck/gcm4j/pull/8 added the required fields. Should be available in Maven Central in a couple of hours.
